Tensors can be created using 

1. tf.constant
2. tf.variable

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

Creating tensors using ***tf.constant***.

Tensors are immutable. i.e. once created they cannot be changed.

***tf.constant*** can be used to create
1. scalar - 0D
2. vector - 1D
3. matriz - 2D
4. tensor - 3D

In [21]:
import tensorflow as tf
import numpy as np

In [10]:
scalar = tf.constant(11)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [5]:
vector = tf.constant([2,4,5])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 5], dtype=int32)>

In [6]:
matrix = tf.constant([[1,2,3],[4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [7]:
tensor = tf.constant ([[[1,2,3],[4,5,6]],[[1,4,3],[5,2,9]],[[0,7,8],[3,1,2]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 4, 3],
        [5, 2, 9]],

       [[0, 7, 8],
        [3, 1, 2]]], dtype=int32)>

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

Creating tensors using ***tf.variable***
These tensors are mutable
All dimension tensors can be creayed using tf.variable

In [18]:
scalar_var = tf.Variable(2)
vector_var = tf.Variable([2,4,56])
matrix_var = tf.Variable([[3,2,4],[8,9,0]])
tensor_var = tf.Variable([[[1,2,3],[4,5,6]],[[1,4,3],[5,2,9]],[[0,7,8],[3,1,2]]])

print(scalar)
print(vector)
print(matrix)
print(tensor)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 2,  4, 56], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[3, 2, 4],
       [8, 9, 0]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 4, 3],
        [5, 2, 9]],

       [[0, 7, 8],
        [3, 1, 2]]], dtype=int32)>


***.assign is used to change the values of tensor if they are created using tf.variable***

In [19]:
vector_var[2].assign(7)
vector_var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 4, 7], dtype=int32)>

In [20]:
matrix_var[1,2].assign(2)
matrix_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[3, 2, 4],
       [8, 9, 2]], dtype=int32)>

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

Creating tensors using ***tf.convert_to_tensor***
Python lists and numpy arrays can be converted to tensors

In [28]:
scalar1 = 3
vector1 = [9,8,0,7]
array1 = np.array([0,6,7])
matrix1 = np.array([[2,1,3],[8,6,5]])

In [29]:
scalar1 = tf.convert_to_tensor(scalar1)
scalar1

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [30]:
vector2 = tf.convert_to_tensor(vector1)
vector1

[9, 8, 0, 7]

In [31]:
array1 = tf.convert_to_tensor(array1)
array1

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 6, 7])>

In [32]:
matrix1 = tf.convert_to_tensor(matrix1)
matrix1

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[2, 1, 3],
       [8, 6, 5]])>

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

Creating ***Random Tensors***
Random Tensors are created by 2 method
1. Normal or Gaussian Distribution
2. Uniform Distribution

**1. Normal Distribution**

A normal distribution, also known as a Gaussian distribution, is a continuous probability distribution that is symmetric around its mean (average) value. It is characterized by a bell-shaped curve, and its shape is completely determined by two parameters: the mean (μ) and the standard deviation (σ). The mean represents the central location of the distribution, and the standard deviation controls the spread or dispersion of the data.

In [34]:
tensor_normal = tf.random.normal(shape=(3,2), mean=10.0)
tensor_normal

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.357622,  9.412098],
       [10.069904, 10.625672],
       [ 9.702013,  9.063157]], dtype=float32)>

In [35]:
tensor_normal1 = tf.random.normal(shape=(4,3,3), mean=18.0)
tensor_normal1

<tf.Tensor: shape=(4, 3, 3), dtype=float32, numpy=
array([[[17.643896, 17.997456, 18.846338],
        [17.26735 , 19.454699, 17.933365],
        [17.964787, 18.342266, 19.108667]],

       [[18.666735, 18.662619, 19.61171 ],
        [17.288456, 19.322964, 19.03079 ],
        [18.184307, 17.4935  , 18.423449]],

       [[20.007282, 19.26679 , 17.72156 ],
        [17.897013, 16.796824, 18.95077 ],
        [15.562476, 15.450766, 18.656694]],

       [[17.944551, 16.304758, 19.783356],
        [17.731684, 18.052237, 18.03784 ],
        [18.532492, 17.453583, 17.468388]]], dtype=float32)>

***2. Uniform Distribution***

A uniform distribution, also known as a rectangular distribution, is a probability distribution in which all outcomes are equally likely. In other words, every possible value within a given range has an equal probability of occurring. The probability density function (PDF) for a continuous uniform distribution is constant over the entire range of possible values and zero elsewhere.

In [38]:
tensor_uniform = tf.random.uniform(shape=(3,4,2), minval = 3.2, maxval = 4.7)
tensor_uniform

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[3.2744935, 4.550191 ],
        [3.773109 , 3.7289038],
        [3.565404 , 4.158935 ],
        [4.2301216, 4.1769047]],

       [[3.5106013, 3.4045067],
        [3.7738192, 3.3318114],
        [3.3029869, 3.5631447],
        [4.087923 , 4.2885494]],

       [[4.553089 , 4.1314936],
        [3.5590858, 4.3050213],
        [3.398963 , 3.3364232],
        [4.1959844, 4.2420874]]], dtype=float32)>

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

Getting ***Basic information*** from a Tensor
1. Data type of tensor - .dtype
2. Shape of tensor - .shape
3. Rank or no. of dimensions of tensor - .ndim
2. Total elements in a tensor - tf.size(tensor_name)

In [43]:
tensor_info = tf.random.uniform(shape =(3,4,2), minval=1, maxval=1.1)
tensor_info

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[1.0073793, 1.0671504],
        [1.0109546, 1.0158958],
        [1.033641 , 1.0567255],
        [1.0031117, 1.0076605]],

       [[1.0698303, 1.0783405],
        [1.0791568, 1.0560254],
        [1.0237141, 1.0288061],
        [1.0561891, 1.084461 ]],

       [[1.0596166, 1.0006526],
        [1.0876992, 1.0061499],
        [1.0817227, 1.0259876],
        [1.0746629, 1.0740496]]], dtype=float32)>

In [45]:
print("Data type of tensor is: ", tensor_info.dtype)
print("Shape of tensor is: ", tensor_info.shape)
print("dimensions of tensor is: ", tensor_info.dtype)
print("Total elements in tensor are: ", tf.size(tensor_info))
print("Total elements in tensor are: ", tf.size(tensor_info).numpy())

Data type of tensor is:  <dtype: 'float32'>
Shape of tensor is:  (3, 4, 2)
dimensions of tensor is:  <dtype: 'float32'>
Total elements in tensor are:  tf.Tensor(24, shape=(), dtype=int32)
Total elements in tensor are:  24


***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

***Indexing*** and ***Slicing*** of tensors

In [48]:
tensor1 = tf.Variable([1,2,3,4,5,6,7,8,9,10])
tensor1

<tf.Variable 'Variable:0' shape=(10,) dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [49]:
tensor1[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [50]:
tensor1

<tf.Variable 'Variable:0' shape=(10,) dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [51]:
tensor1[:5]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [52]:
tensor1[5:]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6,  7,  8,  9, 10], dtype=int32)>

In [53]:
tensor1[2:7]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 4, 5, 6, 7], dtype=int32)>

In [55]:
#Reversing the order of tensor
tensor1[::-1]

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1], dtype=int32)>

In [59]:
# Extract multiple values from multiple indices
indices = tf.constant([2,6,9])
tf.gather(tensor1, indices)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  7, 10], dtype=int32)>

In [60]:
tensor2 = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tensor2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [61]:
tensor2[0,2:]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [62]:
tensor2[1:]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [65]:
tensor2[0:2,:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

Create a tensor using a range of numbers using ***tf.range()***

Syntax will be:

tf.range(start, limit, delta=1, dtype=none, name='range')

1. start - denotes starting value - if not mentioned it considers 0 by default
2. limit - denotes ending value
3. delta - denotes step size

In [66]:
tensor_range1 = tf.range(start=1)
tensor_range1

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>

In [69]:
limit=20
tensor_range2 = tf.range(limit)
tensor_range2

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int32)>

In [70]:
tensor_range3 = tf.range(start = 5, limit=55, delta = 5)
tensor_range3

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50], dtype=int32)>

In [71]:
tensor_range4 = tf.range(start = 55, limit=5, delta = -5)
tensor_range4

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([55, 50, 45, 40, 35, 30, 25, 20, 15, 10], dtype=int32)>

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***
***Typecasting of a tensor***

Builtin datatypes available in tensor

1. tf.float16: 16-bit floating-point.
2. tf.float32: 32-bit floating-point.
3. tf.float64: 64-bit floating-point.
4. tf.int8: 8-bit integer.
5. tf.int16: 16-bit integer.
6. tf.int32: 32-bit integer.
7. tf.int64: 64-bit integer.
8. tf.uint8: 8-bit unsigned integer.
9. tf.uint16: 16-bit unsigned integer.
10. tf.uint32: 32-bit unsigned integer.
11. tf.uint64: 64-bit unsigned integer.
12. tf.bool: Boolean.

Converting a tensor from one datatype to another datatype is called typecasting of a tensor.

It should be noted that tf.cast does not modify original tensor. So we should create a new tensor and then use tf.cast.

In [73]:
tensor_tc = tf.Variable([[1,3,4],[2,3,4]])
tensor_tc

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 3, 4],
       [2, 3, 4]], dtype=int32)>

In [75]:
tensor_tc1 = tf.cast(tensor_tc, dtype=tf.float32)
tensor_tc1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 3., 4.],
       [2., 3., 4.]], dtype=float32)>

In [76]:
tensor_tc2 = tf.random.normal(shape=(3,4), mean = 12)
tensor_tc2

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[12.812162, 11.569508, 11.165329, 10.764576],
       [11.732148, 12.422721, 11.649345, 12.215365],
       [13.280022, 12.633466, 12.250663, 12.538369]], dtype=float32)>

In [77]:
tensor_tc3 = tf.cast(tensor_tc2, dtype=tf.float16)
tensor_tc3

<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
array([[12.81 , 11.57 , 11.164, 10.766],
       [11.734, 12.42 , 11.65 , 12.22 ],
       [13.28 , 12.63 , 12.25 , 12.54 ]], dtype=float16)>

In [79]:
tf.constant(['a', 'b', 'c'])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'a', b'b', b'c'], dtype=object)>

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

***Basic Maths Operations on Tensors***

In [80]:
x = tf.Variable([10., 20., 30.])
y = tf.Variable([1., 2., 3.])

***1. ADDITION***

In [81]:
x+10

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([20., 30., 40.], dtype=float32)>

In [82]:
x+y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([11., 22., 33.], dtype=float32)>

In [84]:
add = tf.add(x,y)
add

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([11., 22., 33.], dtype=float32)>

***2. SUBTRACTION***

In [85]:
x-5

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 5., 15., 25.], dtype=float32)>

In [86]:
y-x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ -9., -18., -27.], dtype=float32)>

In [88]:
sub = tf.subtract(x,y)
sub

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 9., 18., 27.], dtype=float32)>

***3. MULTIPLICATION***

In [89]:
x*20

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([200., 400., 600.], dtype=float32)>

In [90]:
x*y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 40., 90.], dtype=float32)>

In [91]:
mul =tf.multiply(x,y)
mul

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 40., 90.], dtype=float32)>

***4. DIVISION***

In [92]:
x/2

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 5., 10., 15.], dtype=float32)>

In [93]:
x/y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 10., 10.], dtype=float32)>

In [94]:
div = tf.divide(x,y)
div

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 10., 10.], dtype=float32)>

In [95]:
x%2

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [96]:
x%y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

***5. SQUARE***

In [99]:
square = tf.square(x)
square

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([100., 400., 900.], dtype=float32)>

In [100]:
x*x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([100., 400., 900.], dtype=float32)>

***6. POWER***

In [101]:
power = tf.pow(x,3)
power

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 1000.,  8000., 27000.], dtype=float32)>

In [105]:
x**3

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 1000.,  8000., 27000.], dtype=float32)>

***7. SQUARED DIFFERENCE***

In [103]:
sq_di = tf.math.squared_difference(x,y)
sq_di

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 81., 324., 729.], dtype=float32)>

In [104]:
(x-y)**2

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 81., 324., 729.], dtype=float32)>

In [106]:
z = tf.constant([3,67,89,34,21,3,1,0,9,38])

***8. CHECKING INDEX OF MIN AND MAX ELEMENT***

In [108]:
min_el = tf.argmin(z)
min_el

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [109]:
max_el = tf.argmax(z)
max_el

<tf.Tensor: shape=(), dtype=int64, numpy=2>

***9. CHECKING MIN AND MAX ELEMENT***

In [112]:
z[min_el].numpy(), z[max_el].numpy()

(0, 89)

In [113]:
min = tf.reduce_min(z)
min

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [114]:
max = tf.reduce_max(z)
max

<tf.Tensor: shape=(), dtype=int32, numpy=89>

***10. FIND SUM OF ALL ELEMENTS OF A TENSOR***

In [117]:
addition = tf.reduce_sum(z)
addition

<tf.Tensor: shape=(), dtype=int32, numpy=265>

In [124]:
z1 = tf.constant([[3,4,1],[8,9,0]])

add_col = tf.reduce_sum(z1, axis =0)
add_row = tf.reduce_sum(z1, axis=1)
add_col.numpy(), add_row.numpy()

(array([11, 13,  1], dtype=int32), array([ 8, 17], dtype=int32))

***11. MEAN OF A TENSOR***

In [127]:
mean = tf.reduce_mean(z1)
mean_col = tf.reduce_mean(z1, axis = 0)
mean_row = tf.reduce_mean(z1, axis = 1)
mean, mean_col.numpy(), mean_row.numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=4>,
 array([5, 6, 0], dtype=int32),
 array([2, 5], dtype=int32))

***12. VARIANCE OF TENSOR***

Note: To calculate variance we need to import

!pip install tensorflow-probability
import tensorflow_probability as tfp

In [134]:
variance = tfp.stats.variance(z)
variance

<tf.Tensor: shape=(), dtype=int32, numpy=853>

***13. DOT PRODUCT***

In [135]:
x,y

(<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([10., 20., 30.], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>)

In [136]:
dot_pro = tf.reduce_sum(tf.multiply(x,y))
dot_pro

<tf.Tensor: shape=(), dtype=float32, numpy=140.0>

In [141]:
dot_pro1 = tf.tensordot(x,y, axes =1)
dot_pro1

<tf.Tensor: shape=(), dtype=float32, numpy=140.0>

***14. SQUAREROOT OF A TENSOR***

In [146]:
z2 = tf.constant([25.,81.,100.,4.,1.])
z2.numpy()

array([ 25.,  81., 100.,   4.,   1.], dtype=float32)

In [148]:
sqrt = tf.sqrt(z2)
sqrt

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 5.,  9., 10.,  2.,  1.], dtype=float32)>

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

***Basic Matrix Operations on Tensors***

In [149]:
mat1 = tf.constant([[2,4,5],[3,8,7],[0,9,7]])
mat2 = tf.constant([[2,1],[6,4],[1,4]])
mat3 = tf.constant([[2,4,5],[9,7,6]])

***1. Matrix Multiplication***

In [156]:
matmul1 = tf.matmul(mat1, mat2)
matmul1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[33, 38],
       [61, 63],
       [61, 64]], dtype=int32)>

In [157]:
matmul2 = tf.matmul(mat2, mat3)
matmul2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 15, 16],
       [48, 52, 54],
       [38, 32, 29]], dtype=int32)>

In [158]:
#shortcul way of matrix multiplication
mat1 @ mat2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[33, 38],
       [61, 63],
       [61, 64]], dtype=int32)>

In [163]:
#When the shape doesn't match we have to reshape

mat3_reshape = tf.reshape(mat3, shape=(3,2))
matmul3 = tf.matmul(mat1, mat3_reshape)
matmul3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 59,  74],
       [ 95, 126],
       [ 94, 123]], dtype=int32)>

In [160]:
mat1.shape, mat2.shape, mat3.shape

(TensorShape([3, 3]), TensorShape([3, 2]), TensorShape([2, 3]))

***2. TRANSPOSE***

Transpose converts rows to columns and columns to rows

In [164]:
mat3_transpose = tf.transpose(mat3)
mat3_transpose

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 9],
       [4, 7],
       [5, 6]], dtype=int32)>

***3. Create 0s and 1s Matrix***

In [166]:
zeros1 = tf.zeros(shape=(4,5))
zeros1

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [167]:
# creating a zeros matrix same shape as some other matrix

zeros2 = tf.zeros_like(mat3)
zeros2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [168]:
ones1 = tf.ones(shape=(4,5))
ones1

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [169]:
# creating a ones matrix same shape as some other matrix
ones2 = tf.ones_like(mat3)
ones2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

***4. Creating an identical (eye) matrix***

In [170]:
eyes = tf.eye(5)
eyes

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

***5. Concatenate Matrix***

In [173]:
concat_col = tf.concat([mat3, ones2], axis=0)
concat_row = tf.concat([mat3, ones2], axis=1)
concat_col, concat_row

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[2, 4, 5],
        [9, 7, 6],
        [1, 1, 1],
        [1, 1, 1]], dtype=int32)>,
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[2, 4, 5, 1, 1, 1],
        [9, 7, 6, 1, 1, 1]], dtype=int32)>)

***6. Stacking Matrix***

Note: Conacat creates a 2D matrix whereas stack creates a 3D matrix

In [174]:
stack_col = tf.stack([mat3, ones2], axis=0)
stack_row = tf.stack([mat3, ones2], axis=1)
stack_col, stack_row

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[2, 4, 5],
         [9, 7, 6]],
 
        [[1, 1, 1],
         [1, 1, 1]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[2, 4, 5],
         [1, 1, 1]],
 
        [[9, 7, 6],
         [1, 1, 1]]], dtype=int32)>)

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

***KERAS***

1. Keras is a high level, deep learning API.
2. Keras do not support low level operations such as tensor manipulation and differentiation.
3. For these operations Keras relies on tensorflow.

Keras has been integratyed in-built in ***Tensorflow 2.0*** .
So we do not have to import keras differently.

***Key Features of Keras***

***User-Friendly API***: Keras offers a simple, consistent, and intuitive API that makes it easy to quickly prototype and build deep learning models. It's designed to be user-friendly, allowing both beginners and experts to use it effectively.

***Modularity:*** Keras allows for the construction of complex neural network architectures using a modular approach. Neural network layers can be easily added, removed, or connected to create custom models.

***Extensibility:*** Keras is built to be easily extensible. Users can create their own custom layers, loss functions, and metrics. Additionally, Keras models can be seamlessly integrated with lower-level TensorFlow operations.

***Compatibility:*** Keras can run on top of various backends, with TensorFlow being the default backend. This allows users to take advantage of the features and optimizations provided by different deep learning libraries.

***Multiple Input/Output Support:*** Keras supports models with multiple inputs and outputs, making it suitable for a wide range of tasks, including complex architectures like siamese networks and multi-input/multi-output models.

***Built-in Neural Network Layers:*** Keras provides a variety of built-in layers commonly used in neural networks, such as dense (fully connected), convolutional, recurrent, normalization, and activation layers.

***Pre-trained Models:*** Keras includes pre-trained models for popular architectures like VGG16, VGG19, ResNet, and more. These pre-trained models can be used for transfer learning and fine-tuning on new tasks.

***Model Visualization:*** Keras provides utilities for visualizing the architecture of neural networks using tools like plot_model, which can generate graphical representations of models.

***Callbacks:*** Callbacks in Keras allow users to perform actions at different stages of training, such as saving model checkpoints, adjusting learning rates, and early stopping based on performance.

***Ease of Debugging:*** Keras offers clear and informative error messages, making it easier to troubleshoot and debug issues during model development.

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

***WORKFLOW OF KERAS***

***1.Import Dependencies:***
Import the necessary libraries, including Keras and any other libraries you may need for data manipulation, preprocessing, and visualization.

***2. Load and Preprocess Data:***
Load your dataset and preprocess it to prepare it for training. This may involve tasks such as data normalization, resizing, and splitting into training and testing sets.

***3. Build the Model:***
Define the architecture of your neural network using Keras' high-level API. You can stack layers using the Sequential model or create more complex architectures using the functional API.

***4. Compile the Model:***
Configure the learning process by specifying the optimizer, loss function, and metrics. This step prepares the model for training.

***5. Train the Model:***
Train the model on your training data using the fit method. Specify the number of epochs and batch size.
python

***6. Evaluate the Model:***
Evaluate the model's performance on the test set to assess its generalization ability.

***7. Make Predictions:***
Use the trained model to make predictions on new, unseen data.

***8. Save and Load Model (Optional):***
Save your trained model to disk for future use, or load pre-trained models for transfer learning.

***-------------------------------------------------------------------------------------------------------------------------------------------------------------------------***

***1. SEQUENTIAL API***

The Sequential API is the simplest and most commonly used API in Keras. It allows you to create models layer by layer in a linear fashion, where each layer is added sequentially.
Use Case: This API is suitable for simple models with a single input and output path, such as feedforward neural networks.

In [176]:
#Creating a neural network using sequential API 

In [188]:
#importing sequential libraries

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Input

In [178]:
# keras.layers.Dense(units, activation=None, use_bias=True, kernel_initializer="glorot_uniform")

In [189]:
# Define input and output dimensions
input_dim = 50  # Adjust this to the actual dimension of your input features
output_dim = 10

# Generate random training data
X_train = np.random.rand(100, input_dim)
y_train = np.random.randint(0, output_dim, size=(100,))

# Define Sequential Model
model = Sequential()

# Add input layer
model.add(Input(shape=(input_dim,), name="input_Layer"))

# Add first Dense Layer to sequential API
model.add(Dense(512, activation="sigmoid", name="hidden_Layer1"))

# Add second Dense Layer to sequential API
model.add(Dense(128, activation="sigmoid", name="hidden_Layer2"))

# Add output Layer to sequential API
model.add(Dense(output_dim, activation="softmax", name="output_Layer"))

# Display the model summary
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_Layer1 (Dense)       (None, 512)               26112     
                                                                 
 hidden_Layer2 (Dense)       (None, 128)               65664     
                                                                 
 output_Layer (Dense)        (None, 10)                1290      
                                                                 
Total params: 93066 (363.54 KB)
Trainable params: 93066 (363.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


***2. Functional API***

The Functional API provides more flexibility than the Sequential API and allows you to create complex models with multiple inputs and outputs, shared layers, and non-linear connectivity.

Using Functional Api we can create multi-input, multi-output models, layer sharing and model sharing and so on.

Use Case: This API is suitable for more intricate models, including multi-input and multi-output architectures, as well as models with shared layers.

In [190]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

# Define input and output dimensions
input_dim = 50  # Adjust this to the actual dimension of your input features
output_dim = 10

# Generate random training data
X_train = np.random.rand(100, input_dim)
y_train = np.random.randint(0, output_dim, size=(100,))

# Add input layer
input_layer = Input(shape=(input_dim,), name="input_Layer")

# Create Dense Layers
hidden_layer1 = Dense(512, activation="sigmoid", name="Hidden_Layer1")(input_layer)
hidden_layer2 = Dense(512, activation="sigmoid", name="Hidden_Layer2")(hidden_layer1)
output_layer = Dense(output_dim, activation="softmax", name="Output_Layer")(hidden_layer2)

# Define Functional Model
model = Model(inputs=input_layer, outputs=output_layer)

# Display the model summary
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_Layer (InputLayer)    [(None, 50)]              0         
                                                                 
 Hidden_Layer1 (Dense)       (None, 512)               26112     
                                                                 
 Hidden_Layer2 (Dense)       (None, 512)               262656    
                                                                 
 Output_Layer (Dense)        (None, 10)                5130      
                                                                 
Total params: 293898 (1.12 MB)
Trainable params: 293898 (1.12 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


***For displaying plot model***

!pip install pydot

from tensorflow.keras.utils import plot_model

plot_model(model)

***Compiling a Model***

In [196]:
# Compiling a model

model.compile(loss="sparse_categorical_crossentropy", optimizer = "adam", metrics =["accuracy"])

***Training a Model***

In [200]:
batch_sizeize = 128
epochs_num = 5

# Fit a neural network or train a neural network
history = model.fit(X_train, y_train, validation_split = 0.2, epochs = epochs_num, 
                    batch_size = batch_size, verbose =1)

# validation_split divides train and test set in 80% and 20% data set
# epochs denotes no. of times model should run
# batch_size indicates set of data in each batch
# verbose indicates if we eant to see result after each epoch

Epoch 1/5
1/1 [==============================] - 0s 70ms/step - loss: 2.1153 - accuracy: 0.3000 - val_loss: 2.4261 - val_accuracy: 0.0500
Epoch 2/5
1/1 [==============================] - 0s 29ms/step - loss: 2.1086 - accuracy: 0.4000 - val_loss: 2.4297 - val_accuracy: 0.0500
Epoch 3/5
1/1 [==============================] - 0s 28ms/step - loss: 2.1014 - accuracy: 0.4000 - val_loss: 2.4309 - val_accuracy: 0.0500
Epoch 4/5
1/1 [==============================] - 0s 29ms/step - loss: 2.0930 - accuracy: 0.3875 - val_loss: 2.4292 - val_accuracy: 0.0500
Epoch 5/5
1/1 [==============================] - 0s 29ms/step - loss: 2.0840 - accuracy: 0.3750 - val_loss: 2.4250 - val_accuracy: 0.0500


***Evaluating a Trained Network***

In [204]:
score = model.evaluate(x = X_train, y = y_train)
print("Test Score", score[0])
print("Test Score", score[1])

4/4 [==============================] - 0s 3ms/step - loss: 2.1449 - accuracy: 0.2900
Test Score 2.144930839538574
Test Score 0.28999999165534973


***Predictions using trianed neural network***

In [206]:
#y_pred = model.predict(X_test)